# Generated by Django 5.2.5 on 2025-10-15 21:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habit_text', models.CharField(max_length=200, verbose_name='Nombre del hábito')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
            ],
        ),
        migrations.CreateModel(
            name='HabitRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de registro')),
                ('notes', models.CharField(blank=True, max_length=200, verbose_name='Notas u observaciones')),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.habit')),
            ],
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
