# Generated by Django 5.2.5 on 2025-10-24 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_calificacion_alter_habit_pub_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificacion',
            name='comentario',
            field=models.TextField(blank=True, null=True, verbose_name='Comentario'),
        ),
        migrations.AddField(
            model_name='habitrecord',
            name='progress',
            field=models.IntegerField(default=100, verbose_name='Progreso (0-100)'),
        ),
        migrations.AlterField(
            model_name='habitrecord',
            name='notes',
            field=models.CharField(blank=True, max_length=255, verbose_name='Notas'),
        ),
        migrations.AlterField(
            model_name='habitrecord',
            name='record_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora del registro'),
        ),
    ]
